# _config.yml
title: Neil FARMER
description: Neil Farmer CV
baseurl: ""
url: https://Neilstid.github.io

remote_theme: piazzai/cvless

# site settings
taglong: Neil Farmer CV
tagshort: Neil Farmer CV

# author settings
author:
  name: Neil Farmer
  email: neil99.farmer@gmail.com
photo: assets/files/photo.jpg

# social media links
social:
  github: Neilstid
  linkedin: neil-farmer-6869a3150
  orcid: 0009-0003-7775-0491
  cv: assets/files/cv.pdf

# build settings
permalink: pretty
